# To use:
#
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate demommath
#
name: demommath2
channels:
  - defaults
dependencies:
  - python #need to pin to avoid issues with builds
  - cython>=3.0
  - setuptools
  - pkg-config
  - meson-python
  - pip
  - spin
  - ccache
  # For testing
  - pytest
  - pytest-cov
  - pytest-xdist
  - numpy
