package:
  name: demommath
  version: 0.1.7

source:
  path: .

build:
  number: 0
  script: python -m pip install . --no-deps -vv

requirements:
  build:
    - python
  run:
    - python
    - numpy

test:
  imports:
    - demommath
