pin_compatible: False

package:
  name: demommath
  version: 0.2.4

source:
  path: .

build: 
  number: 0
  script: python -m pip install . --no-deps -vv

requirements:
  build:
   - python >=3.6
   - setuptools
   - numpy 
  run:
    - python >=3.6
    - numpy 
test:
  imports:
    - demommath

