name: Python Package CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Update conda and conda-build
      run: |
        conda install -c conda-forge conda conda-build


    - name: Set up Anaconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: demommath1
        environment-file: environment.yml
        channels: defaults
    

    - name: Install Dependencies
      run: |
        conda install --yes python=$PYTHON_VERSION
        
    - name: Display Conda Configuration
      run: conda config --show

    - name: Build and Publish Package
      run: |
        conda install conda-build
        conda build . --output-folder conda-bld
        conda install -y --use-local demommath
        conda install -y anaconda-client
        conda install -y conda-verify
        conda config --set anaconda_upload yes
        anaconda login --username ${{ secrets.CONDA_USERNAME }} --password ${{ secrets.CONDA_PASSWORD }}
        anaconda upload -c velip09 --force /usr/share/miniconda/conda-bld/linux-64/demommath-*.tar.
        
