name: Upload to Anaconda

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Anaconda
      uses: conda-incubator/setup-anaconda@v2
      with:
        anaconda-token: ${{ secrets.CONDA_API_TOKEN }}
        python-version: '3.8'

    - name: Install conda-build
      run: conda install -n base conda-build

    - name: Build and upload to Anaconda
      run: |
        conda build .
        anaconda -t $CONDA_API_TOKEN upload --force -u velip09 -l main /opt/conda/conda-bld/linux-64/*.tar.bz2
