name: Upload to Conda

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: myenv
          environment-file: environment.yml

      - name: Build Conda package
        run: conda build demommath

      - name: Install Conda client
        run: conda install -c conda-forge conda

      - name: Upload to Anaconda
        run: conda install anaconda-client && anaconda -t ${{ secrets.CONDA_API_TOKEN }} upload --user velip09 --label main dist/linux-64/mypackage-*.tar.bz2
        env:
          ANACONDA_TOKEN: ${{ secrets.CONDA_API_TOKEN }}
