name: Python Package CI

on:
  push:
    branches:
      - main

jobs:
  conda:
    name: Build (and upload)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v3.0.1
        with:
          miniforge-variant: Mambaforge
          use-mamba: true
          python-version: 3.9
          channel-priority: strict
          activate-environment: demommath2
          environment-file: environment.yml
          channels: defaults
        
      - name: Install Dependencies
        run: |
          conda install --yes python=$PYTHON_VERSION
        
      - name: Display Conda Configuration
        run: conda config --show

      - name: Build Package
        run: |
          conda install conda-build
          conda install -y anaconda-client
          conda install -y conda-verify
          conda build . --output-folder conda-bld
          
      - name: Upload to PyPI
        if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
        env:
          ANACONDA_USERNAME: __token__
          ANACONDA_PASSWORD: ${{ secrets.CONDA_API_TOKEN }}
          run: |
            anaconda login
            anaconda upload --label dev noarch/*.tar.bz2
